#!/bin/bash -ex

make clean

# With SDCARD_DISABLED
BOARD_ID=SAMD21E_DevBoard MCU=SAMD21E15A SDCARD=SDCARD_DISABLED make all mostly_clean
BOARD_ID=SAMD21E_DevBoard MCU=SAMD21E15B SDCARD=SDCARD_DISABLED make all mostly_clean
BOARD_ID=SAMD21E_DevBoard MCU=SAMD21E16A SDCARD=SDCARD_DISABLED make all mostly_clean
BOARD_ID=SAMD21E_DevBoard MCU=SAMD21E16B SDCARD=SDCARD_DISABLED make all mostly_clean
BOARD_ID=SAMD21E_DevBoard MCU=SAMD21E17A SDCARD=SDCARD_DISABLED make all mostly_clean
BOARD_ID=SAMD21E_DevBoard MCU=SAMD21E18A SDCARD=SDCARD_DISABLED make all mostly_clean
BOARD_ID=SAMD11C_DevBoard MCU=SAMD11C14A SDCARD=SDCARD_DISABLED make all mostly_clean

# With SDCARD_ENABLED
#BOARD_ID=SAMD21E_DevBoard MCU=SAMD21E15A SDCARD=SDCARD_ENABLED make all mostly_clean
#BOARD_ID=SAMD21E_DevBoard MCU=SAMD21E16A SDCARD=SDCARD_ENABLED make all mostly_clean
#BOARD_ID=SAMD21E_DevBoard MCU=SAMD21E17A SDCARD=SDCARD_ENABLED make all mostly_clean
#BOARD_ID=SAMD21E_DevBoard MCU=SAMD21E18A SDCARD=SDCARD_ENABLED make all mostly_clean
#BOARD_ID=SAMD11C_DevBoard MCU=SAMD11C14A SDCARD=SDCARD_ENABLED make all mostly_clean

mv -v *.bin ./binaries/

echo Done building bootloaders!

